JV2017/src/accesoDatos/db4o/Conexion.java
=> Grupo 0: Nueva clase Conexion para db4o

JV2017/src/accesoDatos/db4o/PatronesDAO.java
Actualizacion del metodo alta y cierre de la base de datos en la clase PatronesDAO.java
=> Grupo 1: Actualizacion metodo alta y cierre de bd.

JV2017/src/accesoDatos/db4o/MundosDAO.java
=> Creacion de metodo obtenerTodos

JV2017/src/accesoDatos/db4o/MundosDAO.java
=> creación de método altaMundo

JV2017/src/test/accesoDatos/UsuariosDAOTest.java
Actualización de la clase UsuariosDAOTest
=> Grupo1: Actualización de la clase UsuariosDAOTest

JV2017/src/accesoDatos/db4o/MundosDAO.java
Se ha borrado el método altaMundo y se ha modificado el método alta. Grupo 3
=> Arreglo en clase MundosDAO.

JV2017/src/accesoDatos/db4o/MundosDAO.java
Modificación del método baja para db4o grupo 3
=> Modificación del método baja para db4o

JV2017/src/accesoDatos/db4o/MundosDAO.java
Creación método actualizar, grupo 3
=> Método actualizar

JV2017/src/accesoDatos/db4o/MundosDAO.java
=> Samuel Ecija - MundosDAO - METODO toStringDatosMundos - GRUPO 3

JV2017/src/accesoDatos/db4o/MundosDAO.java
=> Roberto - Creación método toStringIdMundos - Grupo3

JV2017/src/accesoDatos/db4o/MundosDAO.java
Joaquín Garre Hidalgo - Creación método borrarTodosMundos - GRUPO 3
=> Creación método borrarTodosMundos - GRUPO 3

JV2017/src/accesoDatos/mySql/Conexion.java, JV2017/src/accesoDatos/mySql/PatronesDAO.java, JV2017/src/accesoDatos/mySql/UsuariosDAO.java
La clase UsuariosDAO esta con unos errores que los iremos corrigiendo.
=> Grupo 1: Subida de la clase UsuariosDAO, PatronesDAO.

JV2017/src/accesoDatos/mySql/UsuariosDAO.java
Creacion de los metodos crearTablaUsuarios y crearTablaEquivalId para corregir dos de los errores que está dando la clase UsuariosDAO
=> Arreglo de algunos errores en la clase UsuariosDAO

JV2017/src/accesoDatos/mySql/UsuariosDAO.java
Modificación de la clase Alta.
=> Grupo1: Modificada clase Alta

JV2017/src/accesoDatos/mySql/MundosDAO.java
=> Clase MundosDAO, método obtener

JV2017/src/accesoDatos/mySql/MundosDAO.java
Modificación del comentario del método obtenerMundo.
Implementación del método rellenaFilasModelo. GRUPO 3 - Daniel
=> Modificación comentario método y implementación de método rellenaFilasModelo.

JV2017/src/accesoDatos/mySql/MundosDAO.java
=> Crea las columnas del tableModel

JV2017/src/accesoDatos/mySql/MundosDAO.java
Creación método borrar , grupo 3
=> Método borrar, Grupo 3

JV2017/src/accesoDatos/mySql/UsuariosDAO.java
Cambiada clase registrarEquivalenciaId
=> Grupo1: Cambiada clase registrarEquivalenciaId

JV2017/src/accesoDatos/mySql/UsuariosDAO.java
Añadido el método borraFilasModelo()
=> Grupo1: Update UsuariosDAO.java

JV2017/src/accesoDatos/mySql/MundosDAO.java
Se ha implementado el método borraFilasModelo.
=> Implementación de método borraFilasModelo - GRUPO 3
